### ISSUE TITLE
Error writing to csv in run_ppo2_mlp

### ISSUE THREAD

**Issue by nzlz** [AcutronicRobotics/ros2learn#6]
- Branch `dashing`
- Env `MARA-v0`
- Command: `python3 run_ppo2_mlp.py -g -r -v 0.3`

Error
```
Reward:  [-0.89437598]
ee_translation[x, y, z]:  [ 0.399223   -0.09404414  0.63918883]
ee_orientation[w, x, y, z]:  [ -6.60108844e-06   1.57084723e-03  -3.76790331e-06  -1.05699059e-03]
Traceback (most recent call last):
  File "run_ppo2_mlp.py", line 126, in <module>
    csv_file.write_obs(obs[0], csv_files[0], defaults['env_name'])
  File "/home/nestor/ros2learn/experiments/examples/MARA/write_csv.py", line 16, in write_obs
    df.to_csv(f, header=obs_headers, index=False)
  File "/home/nestor/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3020, in to_csv
    formatter.save()
  File "/home/nestor/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 172, in save
    self._save()
  File "/home/nestor/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 274, in _save
    self._save_header()
  File "/home/nestor/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 209, in _save_header
    nalias=len(header))))
ValueError: Writing 24 cols but got 12 aliases
```

**Comment by rkojcev** [comment]
we should clean this out, remove or make it work. It trows errors all the time.

**Comment by Elbarmo** [comment]
I will fix this

**Comment by YueErro** [comment]
This is due to the new stats, now the obs.dim is +12 and the csv writer has the obs size hard coded. We can make it dynamic.

**Comment by Elbarmo** [comment]
This issue should be fixed by https://github.com/AcutronicRobotics/ros2learn/pull/8#issue
